server:
  port: 8081
spring:
  application:
    name: guest
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/guest
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
